language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.1
script:
  - export SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled"
  - cd neo4j ; sbt clean test
  - cd ../orientdb ; sbt clean test
  - cd ../titan ; sbt clean test
  - cd ../tinkergraph ; sbt clean test
